### PR TITLE
Merging new template and styles

### PR DESCRIPTION
**Pull request by psteinb**
currently debugging this PR as of [swcarpentry/lesson-example#155](https://github.com/swcarpentry/lesson-example/issues/155)

### CODE REVIEW

**Comment by psteinb** [comment]
ok, from a rough glance, this looks good to me. Output of `make lesson-check` is humongous, but that is expected for now. Feel free to comment and/or merge. As I am the submitter, I feel bias to accept the merge.

**Comment by ChristinaLK** [comment]
I'm willing to take this on faith, especially if you were able to build + view locally.  Is that the case?

**Comment by psteinb** [comment]
I checked the served page and it looked flawless. of course, a second 
pair of eyes, never hurts.

**Comment by ChristinaLK** [comment]
Sounds good to me!

**Pull request merged**
